// The app speaks Farsi and only Farsi. This replaces the old app's
// three-language switcher: one flat object, no provider, no context, no
// runtime lookup — just an import.

export const fa = {
  appName: "فاکتور ساز",

  auth: {
    signIn: "ورود",
    signInTitle: "ورود به حساب",
    signInSubtitle: "برای ادامه وارد حساب خود شوید",
    username: "نام کاربری",
    password: "رمز عبور",
    signOut: "خروج",
    invalid: "نام کاربری یا رمز عبور اشتباه است",
    inactive: "این حساب غیرفعال شده است",
    missingFields: "نام کاربری و رمز عبور را وارد کنید",
    signingIn: "در حال ورود…",
  },

  nav: {
    receipts: "فاکتورها",
    ledgers: "حساب‌ها",
    priceLists: "فیش مزاد",
    manReceipts: "فیش من",
    clients: "مشتریان",
    products: "محصولات",
    settings: "تنظیمات",
    documents: "اسناد",
    manage: "مدیریت",
  },

  actions: {
    new: "جدید",
    add: "افزودن",
    save: "ذخیره",
    cancel: "انصراف",
    edit: "ویرایش",
    delete: "حذف",
    confirm: "تایید",
    back: "بازگشت",
    create: "ایجاد",
    update: "به‌روزرسانی",
    print: "چاپ",
    exportPdf: "خروجی PDF",
    exportImage: "خروجی تصویر",
    search: "جستجو…",
    addRow: "افزودن ردیف",
    insertAbove: "درج ردیف بالا",
    insertBelow: "درج ردیف پایین",
    duplicate: "تکثیر",
    moveUp: "انتقال به بالا",
    moveDown: "انتقال به پایین",
    remove: "حذف ردیف",
    rowActions: "عملیات ردیف",
    dragRow: "جابه‌جایی ردیف",
    dragHint: "برای جابه‌جایی بکشید",
    exporting: "در حال آماده‌سازی…",
    deleteConfirmTitle: "حذف شود؟",
    deleteConfirmBody: "این کار قابل بازگشت نیست.",
  },

  shell: {
    toggleSidebar: "نمایش/پنهان کردن منو",
    narrowLayout: "چیدمان فشرده",
    expandLayout: "چیدمان تمام‌عرض",
    theme: "ظاهر",
    light: "روشن",
    dark: "تیره",
    system: "سیستم",
    account: "حساب",
    commandHint: "جستجو در اسناد…",
    noResults: "نتیجه‌ای یافت نشد",
  },

  dragHintTitle: "برای جابه‌جایی بکشید",

  sheets: {
    receiptTitle: "فیش",
    ledgerTitle: "حساب",
    priceListTitle: "فیش مزاد",
    manReceiptTitle: "فیش من",
    product: "کالا",
    sign: "علامت",
    count: "تعداد",
    unitWeight: "وزن واحد",
    totalWeight: "وزن کل",
    client: "مشتری",
    invoice: "فاتوره",
    commission: "حق",
    cash: "نقدي",
    balance: "مانده",
    item: "شرح",
    price: "قیمت",
    weightKg: "وزن (کیلو)",
    pricePerMan: "قیمت من",
    pricePerKg: "قیمت کیلو",
    amount: "مبلغ",
    subtotal: "جمع کل",
    expenses: "هزینه‌ها",
    grandTotal: "خالص",
    basketCount: "تعداد باسکت",
    itemsCount: "تعداد اقلام",
  },

  // The حق earned on a sheet type, summed over a window. Shown on the sheet
  // list rather than on a page of its own — it is read while looking at the
  // sheets. فیش مزاد and فیش من each get their own panel, on their own list.
  earnings: {
    title: "درآمد حق",
    descriptionPriceLists: "مجموع حق ثبت‌شده روی فیش‌های مزاد",
    descriptionManReceipts: "مجموع حق ثبت‌شده روی فیش‌های من",
    total: "مجموع حق",
    sheets: "تعداد فیش",
    average: "میانگین هر فیش",
    best: "بیشترین",
    vsPrevious: "نسبت به دوره قبل",
    noPrevious: "دوره قبلی برای مقایسه نیست",
    empty: "در این بازه فیشی ثبت نشده",
    rangeToday: "امروز",
    rangeWeek: "این هفته",
    rangeMonth: "این ماه",
    rangeQuarter: "۳ ماه",
    rangeAll: "همه",
    rangeCustom: "بازه دلخواه",
    rangeLabel: "بازه زمانی",
    pickRange: "انتخاب بازه",
    apply: "اعمال",
    clearRange: "حذف بازه",
    showDetails: "مشاهده جزئیات",
    hideDetails: "بستن جزئیات",
    breakdown: "جزئیات حق",
    who: "شرح / مشتری",
    rowsTruncated: "نمایش {shown} مورد از {total}",
    daily: "روزانه",
    weekly: "هفتگی",
    monthly: "ماهانه",
    oldest: "قدیمی‌ترین",
    newest: "جدیدترین",
  },

  editor: {
    title: "عنوان",
    titlePlaceholder: "نام مشتری یا شرح",
    commissionFlat: "حق (مبلغ)",
    commissionPercent: "حق (درصد)",
    commissionAsPercent: "حق به صورت درصد",
    addExpense: "افزودن هزینه",
    noExpenses: "هزینه‌ای ثبت نشده",
    expenseLabel: "شرح هزینه",
    expenseAmount: "مبلغ",
    saving: "در حال ذخیره…",
    unsavedTitle: "تغییرات ذخیره نشده",
    unsavedBody: "تغییراتی دارید که ذخیره نشده است. بدون ذخیره خارج می‌شوید؟",
    discard: "صرف نظر از تغییرات",
    stay: "ادامه ویرایش",
    newReceipt: "فیش جدید",
    editReceipt: "ویرایش فیش",
    newLedger: "حساب جدید",
    editLedger: "ویرایش حساب",
    newPriceList: "فیش مزاد جدید",
    editPriceList: "ویرایش فیش مزاد",
    newManReceipt: "فیش من جدید",
    editManReceipt: "ویرایش فیش من",
    selectClient: "انتخاب مشتری",
    noClient: "بدون مشتری",
    selectProduct: "انتخاب کالا",
    noProducts: "هنوز کالایی ثبت نشده",
  },

  import: {
    title: "ورود اطلاعات از برنامه قدیمی",
    description: "فایل پشتیبان JSON که از برنامه قدیمی گرفته‌اید را انتخاب کنید.",
    pick: "انتخاب فایل",
    run: "شروع ورود اطلاعات",
    running: "در حال ورود اطلاعات…",
    invalidFile: "فایل معتبر نیست",
    done: "اطلاعات با موفقیت وارد شد",
    warning: "با اجرای دوباره، اطلاعات قبلی این حساب جایگزین می‌شود.",
    summary: "خلاصه",
  },

  clients: {
    title: "مشتریان",
    new: "مشتری جدید",
    edit: "ویرایش مشتری",
    empty: "هنوز مشتری‌ای ثبت نشده",
  },

  products: {
    title: "محصولات",
    new: "کالای جدید",
    edit: "ویرایش کالا",
    empty: "هنوز کالایی ثبت نشده",
    colorName: "نام علامت",
    colorHex: "رنگ",
    unitWeight: "وزن واحد (کیلو)",
  },

  catalog: {
    priceTitle: "کاتالوگ فیش مزاد",
    manTitle: "کاتالوگ فیش من",
    description: "قیمت‌هایی که هنگام ذخیره فیش‌ها یاد گرفته شده‌اند. می‌توانید دستی هم ویرایش کنید.",
    empty: "هنوز چیزی یاد گرفته نشده — یک فیش ذخیره کنید.",
    new: "مورد جدید",
    edit: "ویرایش مورد",
    rate: "نرخ",
  },

  settings: {
    title: "تنظیمات",
    branding: "برندینگ",
    brandingDesc: "ظاهر فیش‌های شما",
    companyName: "نام شرکت",
    primaryColor: "رنگ اصلی",
    accentColor: "رنگ تاکیدی",
    logo: "لوگو",
    logoTooLarge: "حجم لوگو باید کمتر از ۲ مگابایت باشد",
    removeLogo: "حذف لوگو",
    upload: "بارگذاری",
    receiptColumns: "ستون‌های فیش",
    receiptColumnsDesc: "ستون کالا همیشه نمایش داده می‌شود.",
    ledgerColumns: "ستون‌های حساب",
    ledgerColumnsDesc: "ستون نام همیشه نمایش داده می‌شود.",
    showSign: "نمایش علامت",
    showCount: "نمایش تعداد",
    showUnitWeight: "نمایش وزن واحد",
    showTotalWeight: "نمایش وزن کل",
    showInvoice: "نمایش فاتوره",
    showCommission: "نمایش حق",
    showCash: "نمایش نقدي",
    showBalance: "نمایش مانده",
    showDate: "نمایش تاریخ",
    layout: "چیدمان فیش مزاد",
    layoutDesc: "نحوه چیده شدن کالاها در ستون‌های فیش مزاد خروجی.",
    itemsPerColumn: "تعداد کالا در هر ستون",
    maxColumns: "حداکثر ستون",
    users: "کاربران",
    usersDesc: "حساب‌های این سیستم. فقط مدیر می‌تواند حساب بسازد.",
    newUser: "کاربر جدید",
    username: "نام کاربری",
    displayName: "نام نمایشی",
    password: "رمز عبور",
    role: "نقش",
    roleAdmin: "مدیر",
    roleUser: "کاربر",
    active: "فعال",
    inactive: "غیرفعال",
    resetPassword: "تغییر رمز",
    revokeSessions: "خروج از همه دستگاه‌ها",
    sessions: "نشست‌ها",
  },

  common: {
    name: "نام",
    phone: "تلفن",
    address: "آدرس",
    notes: "یادداشت",
    date: "تاریخ",
    pickDate: "انتخاب تاریخ",
    total: "جمع",
    empty: "هنوز چیزی اینجا نیست",
    emptyHint: "برای شروع یک مورد جدید بسازید.",
    noSearchResults: "چیزی با این جستجو پیدا نشد",
    required: "الزامی",
    loading: "در حال بارگذاری…",
    error: "خطایی رخ داد",
    saved: "ذخیره شد",
    deleted: "حذف شد",
    exportFailed: "خروجی گرفتن ناموفق بود",
    number: "شماره",
    items: "اقلام",
  },
} as const

export type Fa = typeof fa
